[package]
name = "graph-server-http"
version.workspace = true
edition.workspace = true

[dependencies]
futures = "0.1.21"
serde = { workspace = true }
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }

[dev-dependencies]
graph-core = { path = "../../core" }
